src/Entity/Project.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProjectRepository;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 */
class Project
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_project;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url_image;

    /**
     * @ORM\Column(type="text", length=255)
     */
    private $description_projet;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="projects")
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lien_github;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lien_projet;

    public function __construct()
    {
        $now = new DateTime('now');
        $this->created_at = $now;


    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameProject(): ?string
    {
        return $this->name_project;
    }

    public function setNameProject(string $name_project): self
    {
        $this->name_project = $name_project;

        return $this;
    }

    public function getUrlImage(): ?string
    {
        return $this->url_image;
    }

    public function setUrlImage(string $url_image): self
    {
        $this->url_image = $url_image;

        return $this;
    }

    public function getDescriptionProjet(): ?string
    {
        return $this->description_projet;
    }

    public function setDescriptionProjet(string $description_projet): self
    {
        $this->description_projet = $description_projet;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getLienGithub(): ?string
    {
        return $this->lien_github;
    }

    public function setLienGithub(string $lien_github): self
    {
        $this->lien_github = $lien_github;

        return $this;
    }

    public function getLienProjet(): ?string
    {
        return $this->lien_projet;
    }

    public function setLienProjet(string $lien_projet): self
    {
        $this->lien_projet = $lien_projet;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Document;
use App\Form\DocumentType;
use App\Repository\ProjectRepository;
use App\Repository\DocumentRepository;
use App\Service\DocumentService;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="app_main")
     */
    public function index(ProjectRepository $projectRepository): Response
    {
        $projects = $projectRepository->findAll();
        return $this->render('main/index.html.twig',[
            "projects" => $projects
        ]);
    }
    /**
     * @Route("/map", name="map")
     */
    public function map(): Response
    {
        return $this->render('main/map.html.twig');
    }
    
    /**
     * @Route("/projets/document", name="document")
     */
    public function document(Request $request, DocumentService $documentService ) : Response{ 
        $document = new Document();
        $form = $this->createForm(DocumentType::class, $document);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $currentUser = $this->getUser();
            $document->setUser($currentUser);
            return $documentService->handleDocumentForm($form);
        }
        return $this->render('main/document.html.twig', [
            'documentForm' => $form->createView(),
        ]);
    }
}

templates/main/document.html.twig
{% extends 'base.html.twig' %}
{% block title %}Génération d'un pdf{% endblock %}
{% block stylesheets %}
{{ encore_entry_link_tags('form') }}
{% endblock %}
{% block body %}

<div class="formContainer">
    <div class="form">
        <div class="card p-4 m-3">
        <div class="message"></div>
            {{ form_start(documentForm , {
                'attr' : 
                     {'id' : 'form_document'}
            }) }}
            {{ form_row(documentForm.title_document, {
                label: 'Titre'
            }) }}
            {{ form_row(documentForm.text, {
                label: 'Texte du document'
            }) }}
            <button type="submit" class="btn btn-success">Générer</button>
            {{ form_end(documentForm) }}
        </div>
    </div>
</div>
<div class="iframeContainer">

</div>
{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Portfolio{% endblock %}

{% block body %}
<section class="filterContainer">
    <div class="filter">
        <div class="h-100 w-100 d-flex justify-content-center align-items-center">
            <h1>Portfolio</h1>
        </div>
    </div>
</section>
<div class="jumbotron text-center bg-blue3">
    <div class="pb-5 pt-3 display-3 white1 ">Mes projets</div>
</div>
<div class="d-flex bg-blue3 mb-5">
    <div class="separatorBlank"></div>
    <div class="prev h1 d-flex align-items-center white1" id="prev"><i class="fa-solid fa-angle-left"></i></div>
    <div class="container py-3">
        <div class="row js-slick-carousel">
            {% for project in projects %}
            <div class="col">
                <div class="card mx-2">

                    <div class="imageContainer"
                        style="background : url('{{project.urlImage}}');background-size : cover;"></div>
                    <div class="card-body p-16to9">
                        <div class="card-body-content">
                            <h5 class="card-title">{{ project.nameProject }}</h5>
                            <p class="card-text m-0">
                                <div class="row h-100">
                                    <div class="col d-flex justify-content-center align-items-center"><a
                                            href="{{ project.lienGithub }}" class="btn"><i
                                                class="fa-brands fa-github h1"></i></a></div>
                                    <div class="col d-flex justify-content-center align-items-center"><a
                                            href="{{ project.lienProjet }}" class="btn"><i
                                                class="fa-solid fa-link h1"></i></a></div>
                                    <div class="col">
                                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam recusandae,
                                            eius quam esse tempora non necessitatibus excepturi magni repudiandae rem
                                            velit natus, corporis ipsum maxime voluptatibus. Soluta voluptates deserunt
                                            aliquam?
                                            Modi consequatur amet iure voluptatibus quia totam, eaque dolores obcaecati
                                            veniam? Excepturi laborum eaque nulla labore, aut necessitatibus dolores
                                            obcaecati reprehenderit hic quasi neque deserunt perspiciatis adipisci
                                            aspernatur, eveniet natus?</p>
                                    </div>

                                </div>
                            </p>

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}



        </div>
    </div>
    <div class="next h1 d-flex align-items-center white1" id="next"><i class="fa-solid fa-angle-right"></i></div>
    <div class="separatorBlank"></div>
</div>
<section class="presentationContainer container-fluid whitesmokeColor">
    <div class="row h-100">
        <div class="col-sm-4">
            <div class="shape">
                <div class="filter2"></div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="h1 text-center py-5">
                Maquettage
            </div>
            <div class="w-100 d-flex justify-content-center">
                <img src="{{asset("build/images/Maquettage.jpg")}}" alt="maquettage" class="imageResize">
            </div>
        </div>
    </div>
</section>
<section class="mediaContainer bg-blue2">
    <div class="h2 text-center pt-5">Réseaux sociaux </div>
    <div class="social-menu d-flex justify-content-center py-5">
        <ul class="d-flex w-50 justify-content-around h1">
            <li><a href="#" target="blank" class="d-flex justify-content-center align-items-center"><i
                        class="fab fa-github"></i></i></a></li>
            <li><a href="#" target="blank" class="d-flex justify-content-center align-items-center"><i
                        class="fab fa-instagram"></i></a></li>
            <li><a href="#" target="blank" class="d-flex justify-content-center align-items-center"><i
                        class="fab fa-linkedin-in"></i></a></li>
            <li><a href="#" class="d-flex justify-content-center align-items-center"><i class="fab fa-codepen"
                        target="blank"></i></a></li>
        </ul>
    </div>
</section>
{% endblock %}

templates/main/map.html.twig
{% extends 'base.html.twig' %}
{% block title %}Map{% endblock %}
  
{% block stylesheets %}

   <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
   integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
   crossorigin=""/>
   {{ encore_entry_link_tags('map') }}
{% endblock %}
{% block body %}

     <div id="map" style="height: 400px;"></div>

{% endblock %}
{% block javascripts %}
     <script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
   integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
   crossorigin="" defer></script>
   {{ encore_entry_script_tags('map') }}
{% endblock %}